name: Build and Push to ACR

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: acrtesting4.azurecr.io
      IMAGE_NAME: myapp-develop
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate Docker tag from branch name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH="${{ github.ref_name }}"
          fi

          SAFE_BRANCH=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's#[^a-z0-9]#-#g')
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${SAFE_BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT


      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME/$IMAGE_NAME:${{ steps.tag.outputs.tag }} ./WebApplication1

      - name: Push Docker image
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:${{ steps.tag.outputs.tag }}

#test new changes