name: Build and Push to ACR

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: acrtesting4.azurecr.io
      IMAGE_NAME: myapp-develop
      TAG: ${{ github.sha }}
      APP_NAME: my-webapp-4-testing
      RESOURCE_GROUP: 4-testing
      SLOT_NAME: feature

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate custom Docker tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH="${{ github.ref_name }}"
          fi

          # Extract prefix and ticket ID: feature/ABC-123-anything → feature-ABC-123
          TYPE=$(echo "$BRANCH" | cut -d'/' -f1)
          TICKET=$(echo "$BRANCH" | cut -d'/' -f2 | cut -d'-' -f1,2)
          SAFE_TAG="${TYPE}-${TICKET}-${GITHUB_SHA::7}"

          echo "tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME/$IMAGE_NAME:${{ steps.tag.outputs.tag }} ./WebApplication1

      - name: Push Docker image
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:${{ steps.tag.outputs.tag }}

  deploy-to-slot:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to existing slot
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --slot ${{ env.SLOT_NAME }} \
            --docker-custom-image-name ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }} \
            --docker-registry-server-url https://${{ env.ACR_NAME }}
