name: Deploy Feature Branch to Slot

on:
  push:
    branches:
      - 'release'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: my-webapp-4-testing
      RESOURCE_GROUP: 4-testing
      SLOT_NAME: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure China
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
